// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEKuFwCr4ra98P12_Id-NEmMUm7MdBqFI',
    appId: '1:102670919556:web:cb04b634c8cf230f85dfd1',
    messagingSenderId: '102670919556',
    projectId: 'phone-auth-ac97e',
    authDomain: 'phone-auth-ac97e.firebaseapp.com',
    storageBucket: 'phone-auth-ac97e.appspot.com',
    measurementId: 'G-VBQLSP3NYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Bf_BX_vp5xueE-uyl8P-7J6nMM89BTs',
    appId: '1:102670919556:android:d506950d08fdcaca85dfd1',
    messagingSenderId: '102670919556',
    projectId: 'phone-auth-ac97e',
    storageBucket: 'phone-auth-ac97e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMdsjdeFXlrOZOBeAYj1hffyDZLMxNFD8',
    appId: '1:102670919556:ios:f5c69dd4d120873c85dfd1',
    messagingSenderId: '102670919556',
    projectId: 'phone-auth-ac97e',
    storageBucket: 'phone-auth-ac97e.appspot.com',
    iosClientId:
        '102670919556-o8ptkicc5kh1amv6aker7otcd6b931lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneNumberAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMdsjdeFXlrOZOBeAYj1hffyDZLMxNFD8',
    appId: '1:102670919556:ios:114be99c5d81e15885dfd1',
    messagingSenderId: '102670919556',
    projectId: 'phone-auth-ac97e',
    storageBucket: 'phone-auth-ac97e.appspot.com',
    iosClientId:
        '102670919556-53vdbdp90pc86naptdkv07rv82fbkggb.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneNumberAuthentication.RunnerTests',
  );
}
